#!/usr/bin/env bash
set -eo pipefail

# If a plugin name was specified
if [ -n $2 ]; then

  # If that plugin exists
  if [ -d "$PLUSHU_ROOT/plugins/$2"]; then

    # If that plugin has an uninstall script
    if [ -f "$PLUSHU_ROOT/plugins/$2/uninstall" ]; then

      # We don't test for executable status, we just let the shell fail if
      # the uninstall script isn't set executable
      "$PLUSHU_ROOT/plugins/$2/uninstall"
    fi

    # Remove the plugin
    rm -rf "$PLUSHU_ROOT/plugins/$2"

  # If that plugin does not exist
  else
    echo "Plugin \"$2\" not found"
    exit 1
  fi

# If no plugin name was specified
else
  echo "Missing name of plugin to uninstall"
  exit 1
fi
