#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

# If a plugin name was specified
if [[ -n $2 ]]; then

  # If that plugin exists
  if [[ -d "$PLUSHU_ROOT/plugins/$2" ]]; then

    # If that plugin has an uninstall script
    if [[ -f "$PLUSHU_ROOT/plugins/$2/uninstall" ]]; then

      # We don't test for executable status, we just
      # let the shell fail if the uninstall script isn't set executable
      PLUSHU_PLUGIN_NAME="$2" "$PLUSHU_ROOT/plugins/$2/uninstall"
    fi

    # Remove the plugin
    rm -rf "$PLUSHU_ROOT/plugins/$2"
    echo "Plugin '$2' uninstalled."

  # If that plugin does not exist
  else
    echo "Plugin '$2' not found" >&2
    exit 1
  fi

# If no plugin name was specified
else
  echo "Missing name of plugin to uninstall" >&2
  exit 1
fi
