#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

# Set the Git directory to read plushu's version from
export GIT_DIR="$PLUSHU_ROOT/.git"

if [ -d $GIT_DIR ]; then
  git describe
else
  echo "No .git directory in $PLUSHU_ROOT, version unknown"
fi
