#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

# For instances where a glob has no matches we want an empty list
shopt -s nullglob

# Get input flag
if [[ "$1" == "-i" ]]; then
  input=true
  shift
fi

# Separate the hook name from the extra arguments
hookname=$1
shift

hooks=()

# Run a hook script, if it's executable, with the input from this invocation
append_hook () {
  if [[ -f "$1" && -x "$1" ]]; then
    hooks+=("$1")
  fi
}

# Run all numbered scripts under directories with this hook's name
append_numbered_hooks () {
  local hookname=$1
  shift

  # Gather every file into an array, prefixing each item with the
  # filename of the script (its position in sort order)
  local filelist=()
  for hook in "$PLUSHU_ROOT"/plugins/*/hooks/"$hookname"/*; do
    filelist+=("${hook##*/}/$hook")
  done

  # Use newline as separator for easy sortability
  local IFS=$'\n'

  # Sort the array numerically
  filelist=(`printf '%s\n' "${filelist[@]}" | sort -n`)

  # Append each script in sorted order
  for hookline in "${filelist[@]}"; do
    append_hook "${hookline#*/}"
  done
}

# Ensure we have a hook name
if [[ -z "$hookname" ]]; then
  echo "plushook: missing hook name" >&2
  exit 1
fi

# Ensure we have a root directory
if [[ -z "$PLUSHU_ROOT" ]]; then
  echo "plushook: PLUSHU_ROOT not defined" >&2
  exit 1
fi

# Run ordered pre-hooks
append_numbered_hooks "pre-$hookname"

# Run other pre-hooks
for hook in "$PLUSHU_ROOT"/plugins/*/hooks/"pre-$hookname"; do
  append_hook "$hook"
done

# Run normal hooks
for hook in "$PLUSHU_ROOT"/plugins/*/hooks/"$hookname"; do
  append_hook "$hook"
done

# Run ordered (post)hooks
append_numbered_hooks "$hookname"

# If we have only one hook
if [[ "${#hooks[@]}" == 1 ]]; then
  # Run it directly, only exposing input if opted in
  subpath=${hooks[0]#$PLUSHU_ROOT/plugins/}
  if [[ -n "$input" ]]; then
    PLUSHU_PLUGIN_NAME=${subpath%%/*} "${hooks[0]}" "$@"
  else
    PLUSHU_PLUGIN_NAME=${subpath%%/*} "${hooks[0]}" "$@" </dev/null
  fi

# If we have more than one hook
elif [[ "${#hooks[@]}" != 0 ]]; then

  # If we're supposed to multiplex stdin, save it to a temp file
  if [[ -n "$input" ]]; then
    input=`mktemp`;
    cat >"$input"
  fi

  # Run each hook, directing our saved input (if we have any) to it
  for hook in "${hooks[@]}"; do
    subpath=${hook#$PLUSHU_ROOT/plugins/}
    if [[ -n "$input" ]]; then
      PLUSHU_PLUGIN_NAME=${subpath%%/*} "$hook" "$@" <"$input"
    else
      PLUSHU_PLUGIN_NAME=${subpath%%/*} "$hook" "$@" </dev/null
    fi
  done

  # If we saved the input to a temporary file, clean up
  if [[ -n "$input" ]]; then
    rm "$input"
  fi
fi
