#!/usr/bin/env bash
set -eo pipefail

# For instances where a glob has no matches we want an empty list
shopt -s nullglob

# Separate the hook name from the extra arguments
hookname=$1
shift

hooks=()

# Run a hook script, if it's executable, with the input from this invocation
append_hook () {
  if [[ -f "$1" && -x "$1" ]]; then
    hooks+=("$1")
  fi
}

# Run all numbered scripts under directories with this hook's name
append_numbered_hooks () {
  local hookname=$1
  shift

  # Gather every file into an array, prefixing each item with the
  # filename of the script (its position in sort order)
  local filelist=()
  for hook in "$PLUSHU_ROOT"/plugins/*/hooks/"$hookname"/*; do
    filelist+=("${hook##*/} $hook")
  done

  # Use newline as separator for easy sortability
  local IFS=$'\n'

  # Sort the array numerically
  filelist=(`printf '%s\n' "${filelist[@]}" | sort -n`)

  # Append each script in sorted order
  for hookline in "${filelist[@]}"; do
    append_hook "${hookline#* }"
  done
}

# Ensure we have a hook name
if [[ -z "$hookname" ]]; then
  echo "runhook: missing hook name" >&2
  exit 1
fi

# Ensure we have a root directory
if [[ -z "$PLUSHU_ROOT" ]]; then
  echo "runhook: PLUSHU_ROOT not defined" >&2
  exit 1
fi

# Run ordered pre-hooks
append_numbered_hooks "pre-$hookname"

# Run other pre-hooks
for hook in "$PLUSHU_ROOT"/plugins/*/hooks/"pre-$hookname"; do
  append_hook "$hook"
done

# Run normal hooks
for hook in "$PLUSHU_ROOT"/plugins/*/hooks/"$hookname"; do
  append_hook "$hook"
done

# Run ordered (post)hooks
append_numbered_hooks "$hookname"

if [[ -n ${hooks[0]} ]]; then
  if [[ -z ${hooks[1]} ]]; then
    subpath=${hooks[0]#$PLUSHU_ROOT/plugins/}
    PLUSHU_PLUGIN_NAME=${subpath%%/*} "{hooks[0]}" "$@"
  else
    input=`mktemp`;
    cat >"$input"
    for hook in "${hooks[@]}"; do
      subpath=${hook#$PLUSHU_ROOT/plugins/}
      PLUSHU_PLUGIN_NAME=${subpath%%/*} "$hook" "$@" <"$input"
    done
    rm "$input"
  fi
fi
